#!/usr/bin/env bash

# TIC Default Study
# =================

export ACTIVE_STUDY=HFPEF
export ACTIVE_SCRIPTS_PATH=$HFPEF_SCRIPTS_PATH
export ACTIVE_PATH=$HFPEF_PATH
export ACTIVE_BIDS_PATH=$HFPEF_BIDS_PATH
export ACTIVE_IMAGE_ANALYSIS_PATH=$HFPEF_IMAGE_ANALYSIS_PATH
export ACTIVE_IMAGE_PROCESSING_PATH=$HFPEF_IMAGE_PROCESSING_PATH
export ACTIVE_IMAGE_PROCESSING_LOG_PATH=$HFPEF_IMAGE_PROCESSING_LOG_PATH
export ACTIVE_MRIQC_PATH=$HFPEF_MRIQC_PATH
export ACTIVE_FMRIPREP_PATH=$HFPEF_FMRIPREP_PATH
export ACTIVE_NETPREP_PATH=$HFPEF_NETPREP_PATH
export ACTIVE_BIDS_CONFIG_FILE=$HFPEF_BIDS_CONFIG_FILE
export ACTIVE_ACT_PATH=$HFPEF_ACT_PATH
export ACTIVE_FMRIPREP_PATH=$HFPEF_FMRIPREP_PATH
export ACTIVE_NETPREP_PATH=$HFPEF_NETPREP_PATH

echo 'Current active study' = $ACTIVE_STUDY
echo
