#!/bin/env bash

# TIC Study Switcher Script
# =========================

source $TIC_STUDIES_PATH/imove/init.sh

export ACTIVE_STUDY=IMOVE
export ACTIVE_ACROSTIC_REGEX=$IMOVE_ACROSTIC_REGEX
export ACTIVE_SCRIPTS_PATH=$IMOVE_SCRIPTS_PATH 
export ACTIVE_PATH=$IMOVE_PATH
export ACTIVE_BIDS_PATH=$IMOVE_BIDS_PATH
export ACTIVE_IMAGE_ANALYSIS_PATH=$IMOVE_IMAGE_ANALYSIS_PATH
export ACTIVE_IMAGE_PROCESSING_PATH=$IMOVE_IMAGE_PROCESSING_PATH
export ACTIVE_IMAGE_PROCESSING_LOG_PATH=$IMOVE_IMAGE_PROCESSING_LOG_PATH

export ACTIVE_QC_PATH=$IMOVE_QC_PATH
export ACTIVE_MRIQC_PATH=$IMOVE_MRIQC_PATH
export ACTIVE_FMRIPREP_PATH=$IMOVE_FMRIPREP_PATH
export ACTIVE_NETPREP_PATH=$IMOVE_NETPREP_PATH
export ACTIVE_ACT_PATH=$IMOVE_ACT_PATH
export ACTIVE_CONN_PATH=$IMOVE_CONN_PATH
export ACTIVE_BIDS_CONFIG_FILE=$IMOVE_BIDS_CONFIG_FILE
export ACTIVE_HEUDICONV_PROTOCOL=$IMOVE_HEUDICONV_PROTOCOL
export ACTIVE_CLEAN_BIDS=$IMOVE_CLEAN_BIDS
export ACTIVE_SINGULARITY_USER_BIND_PATHS=$IMOVE_SINGULARITY_USER_BIND_PATHS
export ACTIVE_SUBJECTS_DIR=$IMOVE_SUBJECTS_DIR
export SUBJECTS_DIR=$IMOVE_SUBJECTS_DIR

export ACTIVE_ACT_PATH=$IMOVE_ACT_PATH
export ACTIVE_FMRIPREP_PATH=$IMOVE_FMRIPREP_PATH
export ACTIVE_NETPREP_PATH=$IMOVE_NETPREP_PATH
